In [3]:
import pandas as pd 
import numpy as np

In [6]:
data = pd.read_csv('play_tennis.csv')
data.drop(columns = ['day'],inplace = True)
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [ ]:
# problem 1 
# Outlook = sunny , temperature = hot , Humidity = High , wind = weak
# play or No play

In [ ]:
# soln 

# P(Yes | sunny,Hot,high,weak)= P(sunny|yes)* P(Hot | yes ) * P(High |yes ) * P(weak | yes ) * p(yes)

# P(No | sunny,Hot,high,weak)= P(sunny|No)* P(Hot | No ) * P(High |No ) * P(weak | No ) * p(No)

# Compare and decide using the maximum a posteriori rule

In [8]:
# problem 2 
# Outlook = Overcast , temperature = Cold , Humidity = Low , wind = weak
# play or No play

In [9]:
# soln 

# P(Yes | overcast,cold,low,weak)= P(overcast|yes)* P(cold | yes ) * P(low|yes ) * P(weak | yes ) * p(yes)
# P(No | overcast,cold,low,weak)= P(overcast|No)* P(cold | No ) * P(low|No ) * P(weak | No ) * p(No)



# Compare and decide using the maximum a posteriori rule

In [10]:
# Training 

# lookup (Dictionary)

# Testing

In [11]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [12]:
py = 9/14
pn = 5/14

In [15]:
# Outlook 

pd.crosstab(data['outlook'] , data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [16]:
Pon = 0 
Prn = 2/5 
Psn = 3/5

Poy = 4/9
Pry = 3/9 
Psy = 2/9

In [17]:
# Temp
pd.crosstab(data['temp'] , data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [18]:
PCoolNo = 1/5 
PHotNo = 2/5 
PMidNo = 2/5

PCoolYes = 3/9 
PHotYes = 2/9 
PMildYes = 4/9

In [19]:
# humidity
pd.crosstab(data['humidity'] , data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [20]:
PHighNo =  4/5 
PNormalNo = 1/5 

PHighYes = 3/9 
PNormalYes = 6/9

In [21]:
#wind
pd.crosstab(data['wind'] , data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [23]:
PStrongNo= 3/5 
PWeakNo = 2/5 

PStrongYes = 3/9
PWeakYes = 6/9

In [26]:
# Outlook = sunny , temperature = hot , Humidity = High , wind = weak

Pyes = py * Psy * PHotYes * PHighYes * PWeakYes
print(Pyes)

0.007054673721340388

In [28]:
Pno = pn * Psn * PHotNo * PHighNo  * PWeakNo
print(Pno)

0.02742857142857143

In [ ]:
# No play