## API 
* application porgramming interface 

An API (Application Programming Interface) is a set of rules and protocols that allows different software systems to communicate. It acts as a bridge between applications, enabling them to exchange data and functionality without exposing internal code. For example, a weather app uses an API to fetch live weather data from a remote server instead of building its own weather system.

In [11]:
pip install requests

Requirement already satisfied: requests in c:\users\patel\appdata\local\programs\python\python313\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\patel\appdata\local\programs\python\python313\lib\site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\patel\appdata\local\programs\python\python313\lib\site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\patel\appdata\local\programs\python\python313\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\patel\appdata\local\programs\python\python313\lib\site-packages (from requests) (2025.1.31)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
import requests

url = "https://api.themoviedb.org/3/movie/top_rated?api_key=a58cf79c3e74d4d0df26fcb57031e303"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers, timeout=15)

print(response.status_code)
print(response.json())

200
{'page': 1, 'results': [{'adult': False, 'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg', 'genre_ids': [18, 80], 'id': 278, 'original_language': 'en', 'original_title': 'The Shawshank Redemption', 'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.', 'popularity': 40.2914, 'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', 'release_date': '1994-09-23', 'title': 'The Shawshank Redemption', 'video': False, 'vote_average': 8.715, 'vote_count': 29684}, {'adult': False, 'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg', 'genre_ids': [18, 80], 'id': 238, 'original_language': 'en', 'original_title': 'The Godfather', 'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.', 'popularity': 37.7366, 'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'release_date': '1972-03-14', 'title': 'The Godfather', 'video': False, 'vote_average': 8.687, 'vote_count': 22416}, {'adult': False, 'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg', 'genre_ids': [18, 80], 'id': 240, 'original_language': 'en', 'original_title': 'The Godfather Part II', 'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 'popularity': 25.3743, 'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg', 'release_date': '1974-12-20', 'title': 'The Godfather Part II', 'video': False, 'vote_average': 8.571, 'vote_count': 13563}, {'adult': False, 'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg', 'genre_ids': [18, 36, 10752], 'id': 424, 'original_language': 'en', 'original_title': "Schindler's List", 'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.', 'popularity': 22.2033, 'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', 'release_date': '1993-12-15', 'title': "Schindler's List", 'video': False, 'vote_average': 8.566, 'vote_count': 17081}, {'adult': False, 'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg', 'genre_ids': [18], 'id': 389, 'original_language': 'en', 'original_title': '12 Angry Men', 'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.", 'popularity': 14.0671, 'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg', 'release_date': '1957-04-10', 'title': '12 Angry Men', 'video': False, 'vote_average': 8.554, 'vote_count': 9722}, {'adult': False, 'backdrop_path': '/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg', 'genre_ids': [16, 10751, 14], 'id': 129, 'original_language': 'ja', 'original_title': '千と千尋の神隠し', 'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.', 'popularity': 20.1045, 'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', 'release_date': '2001-07-20', 'title': 'Spirited Away', 'video': False, 'vote_average': 8.533, 'vote_count': 17921}, {'adult': False, 'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg', 'genre_ids': [28, 80, 53], 'id': 155, 'original_language': 'en', 'original_title': 'The Dark Knight', 'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.', 'popularity': 32.8489, 'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'release_date': '2008-07-16', 'title': 'The Dark Knight', 'video': False, 'vote_average': 8.526, 'vote_count': 35130}, {'adult': False, 'backdrop_path': '/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg', 'genre_ids': [35, 18, 10749], 'id': 19404, 'original_language': 'hi', 'original_title': 'दिलवाले दुल्हनिया ले जायेंगे', 'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.', 'popularity': 8.4355, 'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg', 'release_date': '1995-10-20', 'title': 'Dilwale Dulhania Le Jayenge', 'video': False, 'vote_average': 8.516, 'vote_count': 4554}, {'adult': False, 'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg', 'genre_ids': [14, 18, 80], 'id': 497, 'original_language': 'en', 'original_title': 'The Green Mile', 'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.", 'popularity': 25.1001, 'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg', 'release_date': '1999-12-10', 'title': 'The Green Mile', 'video': False, 'vote_average': 8.504, 'vote_count': 18819}, {'adult': False, 'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg', 'genre_ids': [35, 53, 18], 'id': 496243, 'original_language': 'ko', 'original_title': '기생충', 'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.", 'popularity': 28.0684, 'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 'release_date': '2019-05-30', 'title': 'Parasite', 'video': False, 'vote_average': 8.495, 'vote_count': 20096}, {'adult': False, 'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg', 'genre_ids': [12, 14, 28], 'id': 122, 'original_language': 'en', 'original_title': 'The Lord of the Rings: The Return of the King', 'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b', 'popularity': 34.0884, 'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', 'release_date': '2003-12-17', 'title': 'The Lord of the Rings: The Return of the King', 'video': False, 'vote_average': 8.493, 'vote_count': 25984}, {'adult': False, 'backdrop_path': '/96hiUXEuYsu4tcnvlaY8tEMFM0m.jpg', 'genre_ids': [53, 80, 35], 'id': 680, 'original_language': 'en', 'original_title': 'Pulp Fiction', 'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.", 'popularity': 25.1378, 'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg', 'release_date': '1994-09-10', 'title': 'Pulp Fiction', 'video': False, 'vote_average': 8.486, 'vote_count': 29646}, {'adult': False, 'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg', 'genre_ids': [16, 10749, 18], 'id': 372058, 'original_language': 'ja', 'original_title': '君の名は。', 'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.', 'popularity': 23.9584, 'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg', 'release_date': '2016-08-26', 'title': 'Your Name.', 'video': False, 'vote_average': 8.478, 'vote_count': 12276}, {'adult': False, 'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg', 'genre_ids': [37], 'id': 429, 'original_language': 'it', 'original_title': 'Il buono, il brutto, il cattivo', 'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.', 'popularity': 13.6309, 'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg', 'release_date': '1966-12-22', 'title': 'The Good, the Bad and the Ugly', 'video': False, 'vote_average': 8.5, 'vote_count': 9399}, {'adult': False, 'backdrop_path': '/8sNiAPPYU14PUepFNeSNGUTiHW.jpg', 'genre_ids': [12, 18, 878], 'id': 157336, 'original_language': 'en', 'original_title': 'Interstellar', 'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.', 'popularity': 47.0291, 'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'release_date': '2014-11-05', 'title': 'Interstellar', 'video': False, 'vote_average': 8.467, 'vote_count': 38808}, {'adult': False, 'backdrop_path': '/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg', 'genre_ids': [35, 18, 10749], 'id': 13, 'original_language': 'en', 'original_title': 'Forrest Gump', 'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', 'popularity': 26.5642, 'poster_path': '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg', 'release_date': '1994-06-23', 'title': 'Forrest Gump', 'video': False, 'vote_average': 8.462, 'vote_count': 29195}, {'adult': False, 'backdrop_path': '/gILte6Zd7m1YneIr6MVhh30S9pr.jpg', 'genre_ids': [18, 80], 'id': 769, 'original_language': 'en', 'original_title': 'GoodFellas', 'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.', 'popularity': 23.383, 'poster_path': '/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg', 'release_date': '1990-09-12', 'title': 'GoodFellas', 'video': False, 'vote_average': 8.452, 'vote_count': 13987}, {'adult': False, 'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg', 'genre_ids': [28, 18], 'id': 346, 'original_language': 'ja', 'original_title': '七人の侍', 'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.", 'popularity': 9.6966, 'poster_path': '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg', 'release_date': '1954-04-26', 'title': 'Seven Samurai', 'video': False, 'vote_average': 8.45, 'vote_count': 4101}, {'adult': False, 'backdrop_path': '/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg', 'genre_ids': [16, 18, 10752], 'id': 12477, 'original_language': 'ja', 'original_title': '火垂るの墓', 'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.', 'popularity': 0.0089, 'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg', 'release_date': '1988-04-16', 'title': 'Grave of the Fireflies', 'video': False, 'vote_average': 8.443, 'vote_count': 6340}, {'adult': False, 'backdrop_path': '/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg', 'genre_ids': [35, 18], 'id': 637, 'original_language': 'it', 'original_title': 'La vita è bella', 'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.', 'popularity': 12.5479, 'poster_path': '/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg', 'release_date': '1997-12-20', 'title': 'Life Is Beautiful', 'video': False, 'vote_average': 8.44, 'vote_count': 13773}], 'total_pages': 533, 'total_results': 10644}

In [22]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [23]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,40.2914,8.715,29684
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,37.7366,8.687,22416
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,25.3743,8.571,13563
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,22.2033,8.566,17081
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,14.0671,8.554,9722
5,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,20.1045,8.533,17921
6,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,32.8489,8.526,35130
7,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,8.4355,8.516,4554
8,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,25.1001,8.504,18819
9,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,28.0684,8.495,20096
10,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,34.0884,8.493,25984
11,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,25.1378,8.486,29646
12,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,23.9584,8.478,12276
13,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-22,13.6309,8.500,9399
14,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,47.0291,8.467,38808
15,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,26.5642,8.462,29195
16,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,23.3830,8.452,13987
17,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,9.6966,8.450,4101
18,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.0089,8.443,6340
19,637,Life Is Beautiful,A touching story of an Italian book seller of ...,1997-12-20,12.5479,8.440,13773

In [24]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [34]:
import pandas as pd
import requests
import time

session = requests.Session()
all_movies = []

for i in range(1, 40):   # top_rated usually < 40 pages

    try:
        response = session.get(
            f"https://api.themoviedb.org/3/movie/top_rated?api_key=a58cf79c3e74d4d0df26fcb57031e303&page={i}",
            headers={"User-Agent": "Mozilla/5.0"},
            timeout=20
        )

        if response.status_code != 200:
            break

        data = response.json()

        if not data.get("results"):
            break

        temp_df = pd.DataFrame(data["results"])[
            ['id','title','overview','release_date',
             'popularity','vote_average','vote_count']
        ]

        all_movies.append(temp_df)

        print("Page done:", i)

        time.sleep(1.2)   # ⭐ increase delay

    except Exception as e:
        print("Stopped at page:", i)
        print(e)
        time.sleep(3)
        continue   # retry next page instead of breaking

df = pd.concat(all_movies, ignore_index=True)
print(df.shape)

Stopped at page: 1
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Page done: 2
Page done: 3
Page done: 4
Page done: 5
Page done: 6
Page done: 7
Page done: 8
Page done: 9
Page done: 10
Page done: 11
Page done: 12
Page done: 13
Page done: 14
Page done: 15
Page done: 16
Page done: 17
Page done: 18
Page done: 19
Page done: 20
Page done: 21
Page done: 22
Page done: 23
Page done: 24
Page done: 25
Page done: 26
Page done: 27
Page done: 28
Page done: 29
Page done: 30
Page done: 31
Page done: 32
Page done: 33
Page done: 34
Page done: 35
Page done: 36
Page done: 37
Page done: 38
Page done: 39
(760, 7)

In [35]:
df.to_csv('movies.csv')

In [37]:
pd.read_csv('movies.csv')

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
0,0,550,Fight Club,A ticking-time-bomb insomniac and a slippery s...,1999-10-15,29.4107,8.438,31387
1,1,14537,Harakiri,Down-on-his-luck veteran Tsugumo Hanshirō ente...,1962-09-15,6.4123,8.434,1160
2,2,598,City of God,In the poverty-stricken favelas of Rio de Jane...,2002-08-30,10.6240,8.427,7985
3,3,120,The Lord of the Rings: The Fellowship of the Ring,"Young hobbit Frodo Baggins, after inheriting a...",2001-12-18,30.0130,8.427,26959
4,4,11216,Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",1988-11-17,7.6912,8.425,4720
...,...,...,...,...,...,...,...,...
755,755,705861,Hustle,After discovering a once-in-a-lifetime player ...,2022-06-03,6.6851,7.713,2752
756,756,9800,Philadelphia,Two competing lawyers join forces to sue a pre...,1993-12-22,6.6865,7.713,4531
757,757,49687,Marriage Italian Style,"During the bombing of Naples in World War II, ...",1964-12-18,2.3380,7.712,536
758,758,23832,For Love and Gold,A group of rogues steal a scroll granting its ...,1966-04-07,4.5965,7.711,389
759,759,11171,Mysterious Skin,A teenage hustler and a young man obsessed wit...,2005-03-30,3.9092,7.700,1222