In [96]:
import pandas as pd

df = pd.read_csv("HeartDiseaseTrain-Test.csv")

In [97]:
df.sample(10)

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
305,62,Male,Typical angina,120,267,Lower than 120 mg/ml,ST-T wave abnormality,99,Yes,1.8,Flat,Two,Reversable Defect,0
806,57,Male,Typical angina,150,276,Lower than 120 mg/ml,Normal,112,Yes,0.6,Flat,One,Normal,0
929,60,Male,Typical angina,130,206,Lower than 120 mg/ml,Normal,132,Yes,2.4,Flat,Two,Reversable Defect,0
914,66,Male,Typical angina,112,212,Lower than 120 mg/ml,Normal,132,Yes,0.1,Downsloping,One,Fixed Defect,0
545,48,Male,Atypical angina,110,229,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Upsloping,Zero,Reversable Defect,0
972,52,Male,Asymptomatic,118,186,Lower than 120 mg/ml,Normal,190,No,0.0,Flat,Zero,Normal,1
895,62,Female,Non-anginal pain,130,263,Lower than 120 mg/ml,ST-T wave abnormality,97,No,1.2,Flat,One,Reversable Defect,0
882,57,Male,Typical angina,130,131,Lower than 120 mg/ml,ST-T wave abnormality,115,Yes,1.2,Flat,One,Reversable Defect,0
314,40,Male,Asymptomatic,140,199,Lower than 120 mg/ml,ST-T wave abnormality,178,Yes,1.4,Downsloping,Zero,Reversable Defect,1
478,39,Male,Non-anginal pain,140,321,Lower than 120 mg/ml,Normal,182,No,0.0,Downsloping,Zero,Fixed Defect,1

In [98]:
df['sex'] = df["sex"].map({'Male':1 , 'Female':0})
df['exercise_induced_angina'] = df['exercise_induced_angina'].map({'Yes':1, 'No':0})

In [99]:
df.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,1,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,0,1.0,Downsloping,Two,Reversable Defect,0
1,53,1,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,1,3.1,Upsloping,Zero,Reversable Defect,0
2,70,1,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,1,2.6,Upsloping,Zero,Reversable Defect,0
3,61,1,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,0,0.0,Downsloping,One,Reversable Defect,0
4,62,0,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,0,1.9,Flat,Three,Fixed Defect,0

In [100]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

In [101]:
oe = OrdinalEncoder(categories=[['Upsloping','Flat','Downsloping'],['Zero','One','Two','Three','Four']])

In [102]:
oe.fit(df[['slope', 'vessels_colored_by_flourosopy']])

OrdinalEncoder(categories=[['Upsloping', 'Flat', 'Downsloping'],
                           ['Zero', 'One', 'Two', 'Three', 'Four']])

In [103]:
df[['slope', 'vessels_colored_by_flourosopy']] = oe.transform(
    df[['slope', 'vessels_colored_by_flourosopy']]
)

In [104]:
df.sample(10)

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
975,39,1,Typical angina,118,219,Lower than 120 mg/ml,ST-T wave abnormality,140,0,1.2,1.0,0.0,Reversable Defect,0
250,47,1,Typical angina,110,275,Lower than 120 mg/ml,Normal,118,1,1.0,1.0,1.0,Fixed Defect,0
742,63,1,Typical angina,130,330,Greater than 120 mg/ml,Normal,132,1,1.8,2.0,3.0,Reversable Defect,0
513,54,1,Typical angina,110,206,Lower than 120 mg/ml,Normal,108,1,0.0,1.0,1.0,Fixed Defect,0
996,56,0,Typical angina,134,409,Lower than 120 mg/ml,Normal,150,1,1.9,1.0,2.0,Reversable Defect,0
427,57,1,Non-anginal pain,150,168,Lower than 120 mg/ml,ST-T wave abnormality,174,0,1.6,2.0,0.0,Fixed Defect,1
993,43,1,Typical angina,132,247,Greater than 120 mg/ml,Normal,143,1,0.1,1.0,4.0,Reversable Defect,0
272,39,0,Non-anginal pain,138,220,Lower than 120 mg/ml,ST-T wave abnormality,152,0,0.0,1.0,0.0,Fixed Defect,1
556,59,1,Typical angina,140,177,Lower than 120 mg/ml,ST-T wave abnormality,162,1,0.0,2.0,1.0,Reversable Defect,0
732,51,1,Non-anginal pain,94,227,Lower than 120 mg/ml,ST-T wave abnormality,154,1,0.0,2.0,1.0,Reversable Defect,1

In [105]:
ohe = OneHotEncoder(drop='first', sparse_output=False)

In [106]:
encoded = ohe.fit_transform(
    df[['chest_pain_type','fasting_blood_sugar','rest_ecg','thalassemia']]
)

In [107]:
df.shape

(1025, 14)

In [108]:
encoded_df = pd.DataFrame(
    encoded,
    columns=ohe.get_feature_names_out([
        'chest_pain_type','fasting_blood_sugar','rest_ecg','thalassemia'
    ])
)

In [109]:
encoded_df.sample(4)

,chest_pain_type_Atypical angina,chest_pain_type_Non-anginal pain,chest_pain_type_Typical angina,fasting_blood_sugar_Lower than 120 mg/ml,rest_ecg_Normal,rest_ecg_ST-T wave abnormality,thalassemia_No,thalassemia_Normal,thalassemia_Reversable Defect
214,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
935,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
838,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
160,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0

In [110]:
df = df.drop([
    'chest_pain_type',
    'fasting_blood_sugar',
    'rest_ecg',
    'thalassemia'
], axis=1)

In [111]:
df = df.reset_index(drop=True)
encoded_df = encoded_df.reset_index(drop=True)

In [112]:
df_final = pd.concat([df, encoded_df], axis=1)

In [113]:
df_final.head()

,age,sex,resting_blood_pressure,cholestoral,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,target,chest_pain_type_Atypical angina,chest_pain_type_Non-anginal pain,chest_pain_type_Typical angina,fasting_blood_sugar_Lower than 120 mg/ml,rest_ecg_Normal,rest_ecg_ST-T wave abnormality,thalassemia_No,thalassemia_Normal,thalassemia_Reversable Defect
0,52,1,125,212,168,0,1.0,2.0,2.0,0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
1,53,1,140,203,155,1,3.1,0.0,0.0,0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
2,70,1,145,174,125,1,2.6,0.0,0.0,0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
3,61,1,148,203,161,0,0.0,2.0,1.0,0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
4,62,0,138,294,106,0,1.9,1.0,3.0,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [114]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [115]:
df.describe()

,age,sex,resting_blood_pressure,cholestoral,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,target
count,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,131.611707,246.00000,149.114146,0.336585,1.071512,1.385366,0.754146,0.513171
std,9.072290,0.460373,17.516718,51.59251,23.005724,0.472772,1.175053,0.617755,1.030798,0.500070
min,29.000000,0.000000,94.000000,126.00000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,120.000000,211.00000,132.000000,0.000000,0.000000,1.000000,0.000000,0.000000
50%,56.000000,1.000000,130.000000,240.00000,152.000000,0.000000,0.800000,1.000000,0.000000,1.000000
75%,61.000000,1.000000,140.000000,275.00000,166.000000,1.000000,1.800000,2.000000,1.000000,1.000000
max,77.000000,1.000000,200.000000,564.00000,202.000000,1.000000,6.200000,2.000000,4.000000,1.000000

In [116]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, RobustScaler

ct = ColumnTransformer([
    ("robust", RobustScaler(), ['cholestoral','oldpeak']),
    ("standard", StandardScaler(), ['age','Max_heart_rate'])
],  remainder='passthrough')

In [117]:
df.describe()

,age,sex,resting_blood_pressure,cholestoral,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,target
count,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,131.611707,246.00000,149.114146,0.336585,1.071512,1.385366,0.754146,0.513171
std,9.072290,0.460373,17.516718,51.59251,23.005724,0.472772,1.175053,0.617755,1.030798,0.500070
min,29.000000,0.000000,94.000000,126.00000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,120.000000,211.00000,132.000000,0.000000,0.000000,1.000000,0.000000,0.000000
50%,56.000000,1.000000,130.000000,240.00000,152.000000,0.000000,0.800000,1.000000,0.000000,1.000000
75%,61.000000,1.000000,140.000000,275.00000,166.000000,1.000000,1.800000,2.000000,1.000000,1.000000
max,77.000000,1.000000,200.000000,564.00000,202.000000,1.000000,6.200000,2.000000,4.000000,1.000000

In [118]:
scaled = ct.fit_transform(df_final)

In [119]:
df_scaled = pd.DataFrame(scaled, columns=ct.get_feature_names_out())

In [120]:
df_scaled.columns = [col.split("__")[-1] for col in df_scaled.columns]

In [121]:
df = df_scaled

In [122]:
df.head()

,cholestoral,oldpeak,age,Max_heart_rate,sex,resting_blood_pressure,exercise_induced_angina,slope,vessels_colored_by_flourosopy,target,chest_pain_type_Atypical angina,chest_pain_type_Non-anginal pain,chest_pain_type_Typical angina,fasting_blood_sugar_Lower than 120 mg/ml,rest_ecg_Normal,rest_ecg_ST-T wave abnormality,thalassemia_No,thalassemia_Normal,thalassemia_Reversable Defect
0,-0.437500,0.111111,-0.268437,0.821321,1.0,125.0,0.0,2.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
1,-0.578125,1.277778,-0.158157,0.255968,1.0,140.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
2,-1.031250,1.000000,1.716595,-1.048692,1.0,145.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
3,-0.578125,-0.444444,0.724079,0.516900,1.0,148.0,0.0,2.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
4,0.843750,0.611111,0.834359,-1.874977,0.0,138.0,0.0,1.0,3.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [123]:
df.shape

(1025, 19)

In [124]:
lr = LogisticRegression(max_iter = 1000)

In [125]:
X = df.drop('target', axis=1)
y = df['target']

In [126]:
y.shape

(1025,)

In [127]:
X.shape

(1025, 18)

In [128]:
from sklearn.model_selection import train_test_split

In [129]:
X_train , X_test , y_train , y_test = train_test_split(X , y , random_state=42 , test_size= 0.2)

In [130]:
lr.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [131]:
y_pred = lr.predict(X_test)

In [132]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8048780487804879

In [146]:
from sklearn.metrics import classification_report, confusion_matrix


print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.87      0.72      0.78       102
         1.0       0.76      0.89      0.82       103

    accuracy                           0.80       205
   macro avg       0.81      0.80      0.80       205
weighted avg       0.81      0.80      0.80       205

In [150]:
confusion_matrix(y_test, y_pred)

array([[73, 29],
       [11, 92]])

## Everything in Pipeline

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, RobustScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# 🔹 Features & target
X = df.drop('target', axis=1)
y = df['target']

# 🔹 Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 🔹 Column groups
ohe_cols = ['chest_pain_type','fasting_blood_sugar','rest_ecg','thalassemia']
robust_cols = ['cholestoral','oldpeak']
standard_cols = ['age','Max_heart_rate']

# 🔹 Preprocessing
preprocessor = ColumnTransformer([
    ("ohe", OneHotEncoder(drop='first', handle_unknown='ignore'), ohe_cols),
    ("robust", RobustScaler(), robust_cols),
    ("standard", StandardScaler(), standard_cols)
], remainder='passthrough')

# 🔹 Pipeline
pipe = Pipeline([
    ("preprocessing", preprocessor),
    ("model", LogisticRegression())
])

# 🔹 Train
pipe.fit(X_train, y_train)

# 🔹 Predict
y_pred = pipe.predict(X_test)

# 🔹 Accuracy
from sklearn.metrics import accuracy_score 

print("Accuracy:", accuracy_score(y_test, y_pred))

ValueError: A given column is not a column of the dataframe